// Temporary flat config generated by SunLint
import customPlugin from '/opt/homebrew/lib/node_modules/@sun-asterisk/sunlint/integrations/eslint/plugin/index.js';

export default [
  {
  "files": [
    "**/*.js",
    "**/*.jsx",
    "**/*.ts",
    "**/*.tsx"
  ],
  "languageOptions": {
    "ecmaVersion": "latest",
    "sourceType": "module",
    "parserOptions": {
      "ecmaFeatures": {
        "jsx": true
      }
    }
  },
  "plugins": { "custom": customPlugin },
    "rules": {
    "no-new": "warn",
    "no-constructor-return": "warn"
  }
},
  {
    files: ['**/*.ts', '**/*.tsx'],
    plugins: { "custom": customPlugin },
    languageOptions: {
      parser: (await import('@typescript-eslint/parser')).default,
      ecmaVersion: 'latest',
      sourceType: 'module',
      parserOptions: {
        ecmaFeatures: {
          jsx: true
        }
      }
    },
    rules: {
  "no-new": "warn",
  "no-constructor-return": "warn"
}
  }
];
